language: python

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov-report term-missing

env:
 - CODECOV_TOKEN=$CODECOV_TOKEN

after_success:
 - codecov

